/* This file is generated by python script, do not modify it manually. */

#ifndef __JSON_STRUCT_H__
#define __JSON_STRUCT_H__

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

struct flash 
{
    uint8_t *base_addr;
    int32_t size;
    int32_t sector_size;
    uint8_t *offset_current;
};

struct log 
{
    int32_t console;
    struct flash flash;
};

struct board 
{
    uint8_t *name;
    uint8_t *id;
    uint8_t *version;
};

struct fram_cfg 
{
    struct board board;
    struct log log;
    double test;
    double haha;
    double heihei;
    int32_t a0[5];
    uint8_t *a1[6];
    uint8_t *a2[4];
    double a3[3];
    int32_t a4[5];
};


#ifdef __cplusplus
}
#endif

#endif /* __JSON_STRUCT_H__ */